export const apiMockData = [
    {
        "id": "2024-09-01",
        "day": "domingo",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-02",
        "day": "lunes",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO"
                ],
                "shiftDuration": "00:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "04:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "21:00",
                    "21:15",
                    "21:30",
                    "21:45",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-03",
        "day": "martes",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "05:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "21:00",
                    "21:15",
                    "21:30",
                    "21:45",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO",
                    "PTO"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-04",
        "day": "miércoles",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "05:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "21:00",
                    "21:15",
                    "21:30",
                    "21:45",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-05",
        "day": "jueves",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "05:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "21:00",
                    "21:15",
                    "21:30",
                    "21:45",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "07:30"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-06",
        "day": "viernes",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "07:00",
                    "07:15",
                    "07:30",
                    "07:45",
                    "08:00",
                    "08:15",
                    "08:30",
                    "08:45",
                    "09:00",
                    "09:15",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "05:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "21:00",
                    "21:15",
                    "21:30",
                    "21:45",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "06:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "07:30"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-07",
        "day": "sábado",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "07:30"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            }
        ]
    },
    {
        "id": "2024-09-08",
        "day": "domingo",
        "employees": [
            {
                "id": 1,
                "name": "Ross",
                "wwh": 20,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 3,
                "name": "Monica",
                "wwh": 24,
                "teamWork": "Red",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 5,
                "name": "Chandler",
                "wwh": 40,
                "teamWork": "Black",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "00:00:00"
            },
            {
                "id": 6,
                "name": "Rachel",
                "wwh": 35,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "09:30",
                    "09:45",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "14:00",
                    "14:15",
                    "14:30",
                    "14:45",
                    "15:00",
                    "15:15",
                    "15:30",
                    "15:45",
                    "16:00",
                    "16:15",
                    "16:30",
                    "16:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "07:30"
            },
            {
                "id": 7,
                "name": "Joey",
                "wwh": 8,
                "teamWork": "Blue",
                "workShift": [
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "10:00",
                    "10:15",
                    "10:30",
                    "10:45",
                    "11:00",
                    "11:15",
                    "11:30",
                    "11:45",
                    "12:00",
                    "12:15",
                    "12:30",
                    "12:45",
                    "13:00",
                    "13:15",
                    "13:30",
                    "13:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "17:00",
                    "17:15",
                    "17:30",
                    "17:45",
                    "18:00",
                    "18:15",
                    "18:30",
                    "18:45",
                    "19:00",
                    "19:15",
                    "19:30",
                    "19:45",
                    "20:00",
                    "20:15",
                    "20:30",
                    "20:45",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null",
                    "Null"
                ],
                "shiftDuration": "08:00"
            }
        ]
    }
]

export const timestampMockData = [
    {
        "id": "1",
        "data": {
            "day": "1/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "2/7/2025",
            "periods": [
                {
                    "entry": "09:00",
                    "entryIsMod": "true",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 25200000,
                    "isComplete": true
                }
            ],
            "totalWorked": "7h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "3/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "4/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "durationMs": 0,
                    "isComplete": false
                }
            ],
            "totalWorked": "--",
            "recordsCount": 1,
            "warning": "⚠ Pendiente de revisión"
        }
    },
    {
        "id": "1",
        "data": {
            "day": "7/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "8/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "9/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "10/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "11/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "14/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "15/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "16/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "17/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "18/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "21/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "22/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "23/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "24/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "25/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "28/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "29/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "30/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    },
    {
        "id": "1",
        "data": {
            "day": "31/7/2025",
            "periods": [
                {
                    "entry": "08:00",
                    "entryIsMod": "",
                    "exit": "16:00",
                    "exitIsMod": "",
                    "durationMs": 28800000,
                    "isComplete": true
                }
            ],
            "totalWorked": "8h 0m",
            "recordsCount": 2,
            "warning": null
        }
    }
]

export const lastRecordData = [
    {
        "userId": 29,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "13:00:00",
        "enviadoEn": "2025-07-30T13:00:00.082128",
        "nombre": "John ",
        "apellido": "Roe"
    },
    {
        "userId": 19,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "13:00:00",
        "enviadoEn": "2025-07-30T13:00:00.065131",
        "nombre": "Jhon",
        "apellido": "Doe"
    },
    {
        "userId": 29,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "09:30:00",
        "enviadoEn": "2025-07-30T12:46:28.744682",
        "nombre": "John ",
        "apellido": "Roe"
    },
    {
        "userId": 19,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "09:30:00",
        "enviadoEn": "2025-07-30T12:46:28.732683",
        "nombre": "Jhon",
        "apellido": "Doe"
    },
    {
        "userId": 5,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "11:00:00",
        "enviadoEn": "2025-07-30T12:46:28.714279",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 5,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-30T12:46:28.702811",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 3,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "11:00:00",
        "enviadoEn": "2025-07-30T12:46:28.688811",
        "nombre": "Monica",
        "apellido": "Geller"
    },
    {
        "userId": 3,
        "fecha": "2025-07-30",
        "dia": "WEDNESDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-30T12:46:28.653469",
        "nombre": "Monica",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-07-28",
        "dia": "MONDAY",
        "hora": "11:00:00",
        "enviadoEn": "2025-07-28T11:28:32.632011",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 5,
        "fecha": "2025-07-24",
        "dia": "THURSDAY",
        "hora": "17:00:00",
        "enviadoEn": "2025-07-24T17:35:52.955486",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 1,
        "fecha": "2025-07-24",
        "dia": "THURSDAY",
        "hora": "17:00:00",
        "enviadoEn": "2025-07-24T17:35:52.914485",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-07-24",
        "dia": "THURSDAY",
        "hora": "13:00:00",
        "enviadoEn": "2025-07-24T17:35:52.811096",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 19,
        "fecha": "2025-07-16",
        "dia": "WEDNESDAY",
        "hora": "09:30:00",
        "enviadoEn": "2025-07-16T09:48:43.804826",
        "nombre": "Jhon",
        "apellido": "Doe"
    },
    {
        "userId": 5,
        "fecha": "2025-07-16",
        "dia": "WEDNESDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-16T09:46:37.34059",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 3,
        "fecha": "2025-07-16",
        "dia": "WEDNESDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-16T09:46:37.28859",
        "nombre": "Monica",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-07-16",
        "dia": "WEDNESDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-16T09:45:19.565479",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-07-05",
        "dia": "SATURDAY",
        "hora": "08:00:00",
        "enviadoEn": "2025-07-05T08:42:01.14211",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 19,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "12:00:00",
        "enviadoEn": "2025-06-30T12:09:18.224212",
        "nombre": "Jhon",
        "apellido": "Doe"
    },
    {
        "userId": 29,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "10:00:00",
        "enviadoEn": "2025-06-30T11:56:50.227702",
        "nombre": "John ",
        "apellido": "Roe"
    },
    {
        "userId": 29,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "09:00:00",
        "enviadoEn": "2025-06-30T11:56:50.2157",
        "nombre": "John ",
        "apellido": "Roe"
    },
    {
        "userId": 29,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "07:15:00",
        "enviadoEn": "2025-06-30T11:56:50.2027",
        "nombre": "John ",
        "apellido": "Roe"
    },
    {
        "userId": 19,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "09:00:00",
        "enviadoEn": "2025-06-30T11:56:50.1887",
        "nombre": "Jhon",
        "apellido": "Doe"
    },
    {
        "userId": 7,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "09:30:00",
        "enviadoEn": "2025-06-30T11:56:50.173692",
        "nombre": "Joey",
        "apellido": "Tribiani"
    },
    {
        "userId": 6,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "10:00:00",
        "enviadoEn": "2025-06-30T11:56:50.155173",
        "nombre": "Rachel",
        "apellido": "Green"
    },
    {
        "userId": 6,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "08:30:00",
        "enviadoEn": "2025-06-30T11:56:50.142801",
        "nombre": "Rachel",
        "apellido": "Green"
    },
    {
        "userId": 6,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "07:15:00",
        "enviadoEn": "2025-06-30T11:56:50.131314",
        "nombre": "Rachel",
        "apellido": "Green"
    },
    {
        "userId": 5,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "10:00:00",
        "enviadoEn": "2025-06-30T11:56:50.115804",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 5,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "08:45:00",
        "enviadoEn": "2025-06-30T11:56:50.104768",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 5,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "07:15:00",
        "enviadoEn": "2025-06-30T11:56:50.093768",
        "nombre": "Chandler",
        "apellido": "Bing"
    },
    {
        "userId": 3,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "09:00:00",
        "enviadoEn": "2025-06-30T11:56:50.078767",
        "nombre": "Monica",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-06-30",
        "dia": "MONDAY",
        "hora": "10:15:00",
        "enviadoEn": "2025-06-30T11:56:50.040682",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 6,
        "fecha": "2025-06-28",
        "dia": "SATURDAY",
        "hora": "17:00:00",
        "enviadoEn": "2025-06-28T18:06:18.536374",
        "nombre": "Rachel",
        "apellido": "Green"
    },
    {
        "userId": 6,
        "fecha": "2025-06-28",
        "dia": "SATURDAY",
        "hora": "12:00:00",
        "enviadoEn": "2025-06-28T18:06:18.258382",
        "nombre": "Rachel",
        "apellido": "Green"
    },
    {
        "userId": 3,
        "fecha": "2025-06-28",
        "dia": "SATURDAY",
        "hora": "14:00:00",
        "enviadoEn": "2025-06-28T18:05:20.022831",
        "nombre": "Monica",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-06-28",
        "dia": "SATURDAY",
        "hora": "17:00:00",
        "enviadoEn": "2025-06-28T18:05:19.762552",
        "nombre": "Ross",
        "apellido": "Geller"
    },
    {
        "userId": 1,
        "fecha": "2025-06-28",
        "dia": "SATURDAY",
        "hora": "13:00:00",
        "enviadoEn": "2025-06-28T18:05:19.474994",
        "nombre": "Ross",
        "apellido": "Geller"
    }
]